# Generated by Django 2.0.1 on 2018-01-26 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_auto_20180126_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.CharField(max_length=500)),
                ('edition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='JournalArticle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='description',
            field=models.TextField(help_text='Enter a description of the document', max_length=1000),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Document'),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Maintenance'), ('o', 'On loan'), ('a', 'Available'), ('r', 'Reserved')], default='d', help_text='Document availability', max_length=1),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance'),
        ),
        migrations.AddField(
            model_name='journalarticle',
            name='journal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.Journal'),
        ),
        migrations.AddField(
            model_name='journal',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance'),
        ),
        migrations.AddField(
            model_name='book',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance'),
        ),
    ]
