# Generated by Django 2.0.1 on 2018-01-26 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_auto_20180127_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance', unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance', unique=True),
        ),
        migrations.AlterField(
            model_name='journalarticle',
            name='document_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register.DocumentInstance', unique=True),
        ),
    ]
