# Generated by Django 2.0.1 on 2018-01-26 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_auto_20180127_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterModelOptions(
            name='doctype',
            options={'verbose_name': 'Document Type', 'verbose_name_plural': "Documents' Types"},
        ),
        migrations.AlterModelOptions(
            name='patroninfo',
            options={'verbose_name': "Patron's Information", 'verbose_name_plural': "Patrons' Information"},
        ),
        migrations.AddField(
            model_name='documentinstance',
            name='price',
            field=models.FloatField(help_text='Price in RUB', null=True),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='additional_field1',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='additional_field2',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='additional_field3',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='additional_field4',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='additional_field5',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(help_text='Select tags', to='register.Tag'),
        ),
    ]
