# Generated by Django 2.0.1 on 2018-01-26 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_auto_20180127_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentinstance',
            name='is_reference',
            field=models.BooleanField(default=False),
        ),
    ]
