# Generated by Django 2.0.1 on 2018-01-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_documentinstance_is_reference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='documentinstance',
            name='price',
        ),
        migrations.AlterField(
            model_name='documentinstance',
            name='is_reference',
            field=models.BooleanField(default=False, help_text='Reference materials can not be borrowed.'),
        ),
    ]
