# Generated by Django 2.0.1 on 2018-01-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_auto_20180128_1026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentinstance',
            old_name='holder',
            new_name='borrower',
        ),
        migrations.AddField(
            model_name='patroninfo',
            name='name',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
