# Generated by Django 2.0.1 on 2018-01-28 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_patroninfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patroninfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
